---

loopbacks:
  - { iface: loopback0, addr: 192.168.20.30, mask: 32, description: Router-ID }

fabric_interfaces:
  - { iface: Ethernet1/1 }
  - { iface: Ethernet1/2 }
  - { iface: Ethernet1/3 }
  - { iface: Ethernet1/4 }

host_interfaces:
  - { iface: port-channel 1, members: ["Ethernet1/5", "Ethernet1/6"] }
